### ISSUE TITLE
the result is different than the c program?

### ISSUE THREAD

**Issue by ninankara** [keremdemirer/3dbinpackingjs#4]
Hi,

I am developing 3D bin packing algorithm based on the same reference with  yours. However, I tried your program as main reference because it is easier. And I found the result is different than the paper in the original project.

https://github.com/wknechtel/3d-bin-pack

I tried 9 boxes as shown as in the paper
1. 40,52,36 - 3pcs
2. 70,104,24 - 4pcs
3. 14,104,48 - 2pcs

container size is 84, 104, 96

based on the paper, the result should have packed 6 boxes. but i tried with this program and nothing to be packed.

**Comment by keremdemirer** [comment]
Can you try with this commit? https://github.com/keremdemirer/3dbinpackingjs/commit/6536c0a0384f0b19c294892242808fe85f0a1a73

**Comment by ninankara** [comment]
yes, I tried using the newest commit

**Comment by keremdemirer** [comment]
Duplicate #3
